// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "paths": {
        "/api/v1/barang": {
            "get": {
                "description": "Mendapatkan semua data barang",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Barang"],
                "summary": "List semua barang",
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}
                }
            },
            "post": {
                "description": "Menambahkan barang baru",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Barang"],
                "summary": "Tambah barang",
                "parameters": [
                    {"description": "Data barang", "name": "body", "in": "body", "required": true,
                     "schema": {"$ref": "#/definitions/v1.CreateBarangRequest"}}
                ],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/v1.Response"}}
                }
            }
        },
        "/api/v1/barang/{id}": {
            "get": {
                "tags": ["Barang"], "summary": "Get barang by ID",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}
            },
            "put": {
                "tags": ["Barang"], "summary": "Update barang",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"},
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/v1.UpdateBarangRequest"}}
                ],
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}
            },
            "delete": {
                "tags": ["Barang"], "summary": "Hapus barang",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}
            }
        },
        "/api/v1/users": {
            "get": {"tags": ["Users"], "summary": "List semua user",
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}},
            "post": {"tags": ["Users"], "summary": "Tambah user",
                "parameters": [{"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/v1.CreateUserRequest"}}],
                "responses": {"201": {"description": "Created", "schema": {"$ref": "#/definitions/v1.Response"}}}}
        },
        "/api/v1/users/{id}": {
            "get": {"tags": ["Users"], "summary": "Get user by ID",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}},
            "put": {"tags": ["Users"], "summary": "Update user",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"},
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/v1.UpdateUserRequest"}}
                ],
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}},
            "delete": {"tags": ["Users"], "summary": "Hapus user",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}}
        },
        "/api/v1/pembelian": {
            "get": {"tags": ["Pembelian"], "summary": "List semua pembelian",
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}},
            "post": {"tags": ["Pembelian"], "summary": "Tambah pembelian",
                "parameters": [{"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/v1.CreatePembelianRequest"}}],
                "responses": {"201": {"description": "Created", "schema": {"$ref": "#/definitions/v1.Response"}}}}
        },
        "/api/v1/pembelian/{id}": {
            "get": {"tags": ["Pembelian"], "summary": "Get pembelian by ID",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer"}],
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}},
            "put": {"tags": ["Pembelian"], "summary": "Update pembelian",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/v1.UpdatePembelianRequest"}}
                ],
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}},
            "delete": {"tags": ["Pembelian"], "summary": "Hapus pembelian",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer"}],
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}}
        },
        "/api/v1/karat": {
            "get": {"tags": ["Karat"], "summary": "List semua karat",
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}},
            "post": {"tags": ["Karat"], "summary": "Tambah karat",
                "parameters": [{"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/v1.CreateKaratRequest"}}],
                "responses": {"201": {"description": "Created", "schema": {"$ref": "#/definitions/v1.Response"}}}}
        },
        "/api/v1/karat/{id}": {
            "get": {"tags": ["Karat"], "summary": "Get karat by ID",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK"}}},
            "put": {"tags": ["Karat"], "summary": "Update karat",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK"}}},
            "delete": {"tags": ["Karat"], "summary": "Hapus karat",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK"}}}
        },
        "/api/v1/baki": {
            "get": {"tags": ["Baki"], "summary": "List semua baki",
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}},
            "post": {"tags": ["Baki"], "summary": "Tambah baki",
                "parameters": [{"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/v1.CreateBakiRequest"}}],
                "responses": {"201": {"description": "Created"}}}
        },
        "/api/v1/baki/{id}": {
            "get": {"tags": ["Baki"], "summary": "Get baki by ID",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK"}}},
            "put": {"tags": ["Baki"], "summary": "Update baki",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK"}}},
            "delete": {"tags": ["Baki"], "summary": "Hapus baki",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK"}}}
        },
        "/api/v1/penjualan": {
            "get": {"tags": ["Penjualan"], "summary": "List semua penjualan",
                "responses": {"200": {"description": "OK", "schema": {"$ref": "#/definitions/v1.Response"}}}},
            "post": {"tags": ["Penjualan"], "summary": "Tambah penjualan",
                "parameters": [{"name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/v1.CreatePenjualanRequest"}}],
                "responses": {"201": {"description": "Created"}}}
        },
        "/api/v1/penjualan/{id}": {
            "get": {"tags": ["Penjualan"], "summary": "Get penjualan by ID",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK"}}},
            "put": {"tags": ["Penjualan"], "summary": "Update penjualan",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK"}}},
            "delete": {"tags": ["Penjualan"], "summary": "Hapus penjualan",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "string"}],
                "responses": {"200": {"description": "OK"}}}
        }
    },
    "definitions": {
        "v1.Response": {
            "type": "object",
            "properties": {
                "code": {"type": "integer", "example": 200},
                "message": {"type": "string", "example": "success"},
                "data": {}
            }
        },
        "v1.CreateBarangRequest": {
            "type": "object",
            "properties": {
                "barcode": {"type": "string", "example": "BC001"},
                "nama": {"type": "string", "example": "Gelang Emas"},
                "karat": {"type": "integer", "example": 24},
                "berat": {"type": "number", "example": 5.5},
                "harga": {"type": "integer", "example": 5000000},
                "photo": {"type": "string"},
                "kondisi": {"type": "string", "example": "baru"},
                "pembelian_id": {"type": "string"},
                "baki_id": {"type": "string"},
                "grup_id": {"type": "string"}
            }
        },
        "v1.UpdateBarangRequest": {
            "type": "object",
            "properties": {
                "barcode": {"type": "string"},
                "nama": {"type": "string"},
                "karat": {"type": "integer"},
                "berat": {"type": "number"},
                "harga": {"type": "integer"},
                "photo": {"type": "string"},
                "kondisi": {"type": "string"},
                "pembelian_id": {"type": "string"},
                "baki_id": {"type": "string"},
                "grup_id": {"type": "string"}
            }
        },
        "v1.CreateUserRequest": {
            "type": "object",
            "properties": {
                "nama": {"type": "string", "example": "Budi Santoso"},
                "username": {"type": "string", "example": "budi"},
                "password": {"type": "string", "example": "secret123"},
                "role": {"type": "string", "example": "kasir"}
            }
        },
        "v1.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "nama": {"type": "string"},
                "username": {"type": "string"},
                "role": {"type": "string"}
            }
        },
        "v1.CreatePembelianRequest": {
            "type": "object",
            "properties": {
                "no_faktur": {"type": "string", "example": "INV-2024-001"},
                "nama": {"type": "string", "example": "Toko Mas Jaya"},
                "tipe_pemasok": {"type": "string", "example": "supplier"},
                "harga_deal": {"type": "integer", "example": 10000000}
            }
        },
        "v1.UpdatePembelianRequest": {
            "type": "object",
            "properties": {
                "no_faktur": {"type": "string"},
                "nama": {"type": "string"},
                "tipe_pemasok": {"type": "string"},
                "harga_deal": {"type": "integer"}
            }
        },
        "v1.CreateKaratRequest": {
            "type": "object",
            "properties": {
                "name": {"type": "string", "example": "24K"},
                "harga": {"type": "integer", "example": 1000000}
            }
        },
        "v1.UpdateKaratRequest": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "harga": {"type": "integer"}
            }
        },
        "v1.CreateBakiRequest": {
            "type": "object",
            "properties": {
                "nama": {"type": "string", "example": "Baki 1"}
            }
        },
        "v1.UpdateBakiRequest": {
            "type": "object",
            "properties": {
                "nama": {"type": "string"}
            }
        },
        "v1.CreatePenjualanRequest": {
            "type": "object",
            "properties": {
                "no_faktur": {"type": "string", "example": "SELL-2024-001"},
                "nama": {"type": "string", "example": "Pelanggan A"},
                "total_harga": {"type": "integer", "example": 5000000},
                "kode_sales": {"type": "string", "example": "550e8400-e29b-41d4-a716-446655440000"}
            }
        },
        "v1.UpdatePenjualanRequest": {
            "type": "object",
            "properties": {
                "no_faktur": {"type": "string"},
                "nama": {"type": "string"},
                "total_harga": {"type": "integer"},
                "kode_sales": {"type": "string"}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Schemes:          []string{},
	Title:            "Jason Jewelry API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
